In [5]:
import pandas as pd
df = pd.read_pickle("./geotweets_labeled")

In [7]:
df.head()

,date,text,day_of_week,hour,safe
date,,,,,
2020-03-23 00:01:25-04:00,2020-03-23 00:01:25-04:00,"""THE DUDE"" HUCKLEBERRY LETTERPRESS Mar 14, 201...",Monday,0,NaN
2020-03-23 00:04:33-04:00,2020-03-23 00:04:33-04:00,"""E PLURIBUS DOLEMITE"" TOWER RECORDS' PULSE MAG...",Monday,0,NaN
2020-03-23 00:12:56-04:00,2020-03-23 00:12:56-04:00,"""EARBUD HORROR"" REVOLVER Jun 30, 2014 ART DIRE...",Monday,0,NaN
2020-03-23 00:18:54-04:00,2020-03-23 00:18:54-04:00,"""ECCE JACKO"" ROYAL FLUSH Apr 8, 2008 ART DIREC...",Monday,0,NaN
2020-03-23 00:20:21-04:00,2020-03-23 00:20:21-04:00,"""ECCE RUDY"" NEW YORK PRESS Feb 18, 2001 ART DI...",Monday,0,NaN

In [33]:
odd_hrs = df[(df['day_of_week'] == 'Monday') & ((df['hour'] == 23) | (df['hour'] == 0))]

In [34]:
odd_hrs

,date,text,day_of_week,hour,safe
date,,,,,
2020-03-23 00:01:25-04:00,2020-03-23 00:01:25-04:00,"""THE DUDE"" HUCKLEBERRY LETTERPRESS Mar 14, 201...",Monday,0,NaN
2020-03-23 00:04:33-04:00,2020-03-23 00:04:33-04:00,"""E PLURIBUS DOLEMITE"" TOWER RECORDS' PULSE MAG...",Monday,0,NaN
2020-03-23 00:12:56-04:00,2020-03-23 00:12:56-04:00,"""EARBUD HORROR"" REVOLVER Jun 30, 2014 ART DIRE...",Monday,0,NaN
2020-03-23 00:18:54-04:00,2020-03-23 00:18:54-04:00,"""ECCE JACKO"" ROYAL FLUSH Apr 8, 2008 ART DIREC...",Monday,0,NaN
2020-03-23 00:20:21-04:00,2020-03-23 00:20:21-04:00,"""ECCE RUDY"" NEW YORK PRESS Feb 18, 2001 ART DI...",Monday,0,NaN
2020-03-23 00:21:42-04:00,2020-03-23 00:21:42-04:00,"""EGYPTIAN EXPULSION"" NEW YORK PRESS Dec 22, 20...",Monday,0,NaN
2020-03-23 00:22:54-04:00,2020-03-23 00:22:54-04:00,"""FRANKENSTEIN AT CBGBS"" ELECTRIC FRANKENSTEIN ...",Monday,0,NaN
2020-03-23 00:25:40-04:00,2020-03-23 00:25:40-04:00,"""BRIDE OF FRANKENSTEIN POLE DANCER"" ELECTRIC F...",Monday,0,NaN
2020-03-23 00:28:13-04:00,2020-03-23 00:28:13-04:00,"""ELEVATOR REPAIRMAN"" HABITAT Jul 28, 2003 ART ...",Monday,0,NaN
2020-03-23 00:30:13-04:00,2020-03-23 00:30:13-04:00,"""ELTON JOHN"" OUT MAGAZINE Feb 10, 2003 ART DIR...",Monday,0,NaN
2020-03-23 00:31:46-04:00,2020-03-23 00:31:46-04:00,"""ELVIS COSTELLO"" TOWER RECORDS' PULSE MAGAZINE...",Monday,0,NaN
2020-03-23 23:30:52-04:00,2020-03-23 23:30:52-04:00,"""ENEMY/BRAKE OUT POSTER"" Aug 2, 1990 #ILLO #IL...",Monday,23,NaN
2020-03-23 23:32:42-04:00,2020-03-23 23:32:42-04:00,"""EQUITY TAROT"" FORTUNE Jan 22, 2007 ART DIRECT...",Monday,23,NaN
2020-03-23 23:34:39-04:00,2020-03-23 23:34:39-04:00,"""ESCAPE ARTIST"" NETWORK COMPUTING Oct 3, 2001 ...",Monday,23,NaN
2020-03-23 23:37:25-04:00,2020-03-23 23:37:25-04:00,"""ESTHER DYSON"" ARTBYTE Dec 1, 2000 ART DIRECTI...",Monday,23,NaN
2020-03-23 23:39:37-04:00,2020-03-23 23:39:37-04:00,"""E.T. BICYCLE CRASH"" THE WALL STREET JOURNAL A...",Monday,23,NaN
2020-03-23 23:40:49-04:00,2020-03-23 23:40:49-04:00,"""ETHNIC CHOW"" NEW YORK MAGAZINE Apr 7, 1998 AR...",Monday,23,NaN
2020-03-23 23:43:40-04:00,2020-03-23 23:43:40-04:00,"""EVICTION"" PORTLAND MERCURY Oct 11, 2006 ART D...",Monday,23,NaN
2020-03-23 23:45:29-04:00,2020-03-23 23:45:29-04:00,"""EYE IN THE SKY"" SAN FRANCISCO BAY GUARDIAN Ja...",Monday,23,NaN
2020-03-23 23:47:36-04:00,2020-03-23 23:47:36-04:00,"""ECCE BOZO"" FALSE VIRGINS POSTER Jul 13, 1990 ...",Monday,23,NaN
2020-03-23 23:48:46-04:00,2020-03-23 23:48:46-04:00,"""FLOATING BABY"" FALSE VIRGINS POSTER Jun 1, 19...",Monday,23,NaN
2020-03-23 23:50:11-04:00,2020-03-23 23:50:11-04:00,"""MADONNA AND CHILD"" FALSE VIRGINS POSTER Aug 2...",Monday,23,NaN
2020-03-23 23:51:44-04:00,2020-03-23 23:51:44-04:00,"""WOTAN"" FALSE VIRGINS POSTER Nov 24, 1990 ART ...",Monday,23,NaN